name: Integration

on: #when trigger
  pull_request:
     branches: #merge to main branch
       - main
     

#what job do we want to run, if any error occurs in this job, it will stop, and show error
jobs:
  build: #first job is build
    runs-on: ubuntu-latest # where to run this job 
    steps: # steps we need to take to run this job  
      - uses: actions/checkout@v3 # checkout branch
      - uses: actions/setup-node@v2 # to setup a node inside of this ubuntu server
      - name: Install dependencies # npm run install
        run: npm install
      - name: Build app
        run: npm run build
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

    
